#!/usr/bin/env python3
"""Generates 0006_seed.sql from the verified list, and COUNTS instead of asserting.

The file `seed-coasters.md` said 44 coasters, 9 parks and 11 manufacturers.
Counting its own list: it does not match. That is why this script exists, and why
the TDD's numbers come from here and not from anyone's memory.
"""
import collections

# (coaster, park, manufacturer or None, type)
D = [
 # United Kingdom
 ("Nemesis Reborn","Alton Towers","Bolliger & Mabillard","steel"),
 ("Oblivion","Alton Towers","Bolliger & Mabillard","steel"),
 ("The Smiler","Alton Towers","Gerstlauer","steel"),
 ("Wicker Man","Alton Towers","Great Coasters International","wooden"),
 ("Rita","Alton Towers","Intamin","steel"),
 ("Th13teen","Alton Towers","Intamin","steel"),
 ("Stealth","Thorpe Park","Intamin","steel"),
 ("Nemesis Inferno","Thorpe Park","Bolliger & Mabillard","steel"),
 ("Colossus","Thorpe Park","Intamin","steel"),
 ("The Swarm","Thorpe Park","Bolliger & Mabillard","steel"),
 ("Hyperia","Thorpe Park","Mack Rides","steel"),
 ("The Big One","Blackpool Pleasure Beach","Arrow Dynamics","steel"),
 ("Icon","Blackpool Pleasure Beach","Mack Rides","steel"),
 ("Grand National","Blackpool Pleasure Beach","Charles Paige","wooden"),
 ("Big Dipper","Blackpool Pleasure Beach","John A. Miller","wooden"),
 ("Mandrill Mayhem","Chessington World of Adventures","Vekoma","steel"),
 ("Vampire","Chessington World of Adventures","Arrow Dynamics","steel"),
 # United States
 ("The Incredible Hulk Coaster","Universal Islands of Adventure","Bolliger & Mabillard","steel"),
 ("Jurassic World VelociCoaster","Universal Islands of Adventure","Intamin","steel"),
 ("Hagrid's Magical Creatures Motorbike Adventure","Universal Islands of Adventure","Intamin","steel"),
 ("Hollywood Rip Ride Rockit","Universal Studios Florida","Maurer Rides","steel"),
 ("Revenge of the Mummy","Universal Studios Florida","Premier Rides","steel"),
 ("Stardust Racers","Universal Epic Universe","Mack Rides","steel"),
 ("Curse of the Werewolf","Universal Epic Universe","Mack Rides","steel"),
 ("Hiccup's Wing Gliders","Universal Epic Universe","Intamin","steel"),
 ("Mine-Cart Madness","Universal Epic Universe","Intamin","steel"),
 ("Mako","SeaWorld Orlando","Bolliger & Mabillard","steel"),
 ("Manta","SeaWorld Orlando","Bolliger & Mabillard","steel"),
 ("Kraken","SeaWorld Orlando","Bolliger & Mabillard","steel"),
 ("Ice Breaker","SeaWorld Orlando","Premier Rides","steel"),
 ("Pipeline: The Surf Coaster","SeaWorld Orlando","Bolliger & Mabillard","steel"),
 ("Iron Gwazi","Busch Gardens Tampa Bay","Rocky Mountain Construction","hybrid"),
 ("SheiKra","Busch Gardens Tampa Bay","Bolliger & Mabillard","steel"),
 ("Montu","Busch Gardens Tampa Bay","Bolliger & Mabillard","steel"),
 ("Kumba","Busch Gardens Tampa Bay","Bolliger & Mabillard","steel"),
 ("Cheetah Hunt","Busch Gardens Tampa Bay","Intamin","steel"),
 ("Skyrush","Hersheypark","Intamin","steel"),
 ("Candymonium","Hersheypark","Bolliger & Mabillard","steel"),
 ("Wildcat's Revenge","Hersheypark","Rocky Mountain Construction","hybrid"),
 ("Great Bear","Hersheypark","Bolliger & Mabillard","steel"),
 ("Storm Runner","Hersheypark","Intamin","steel"),
 ("Fahrenheit","Hersheypark","Intamin","steel"),
 ("Lightning Racer","Hersheypark","Great Coasters International","wooden"),
 ("Comet","Hersheypark","Philadelphia Toboggan Coasters","wooden"),
 ("Laff Trakk","Hersheypark","Maurer Rides","steel"),
 ("Sooperdooperlooper","Hersheypark","Schwarzkopf","steel"),
]

COUNTRY = {p:"GB" for p in ["Alton Towers","Thorpe Park","Blackpool Pleasure Beach",
                         "Chessington World of Adventures"]}
COUNTRY.update({p:"US" for p in ["Universal Islands of Adventure","Universal Studios Florida",
                              "Universal Epic Universe","SeaWorld Orlando",
                              "Busch Gardens Tampa Bay","Hersheypark"]})

parks_seen  = sorted({p for _,p,_,_ in D})
fabs     = sorted({f for _,_,f,_ in D if f})
types_seen    = sorted({t for _,_,_,t in D})
countries   = sorted(set(COUNTRY.values()))
assert all(p in COUNTRY for p in parks_seen), "park without a country"
assert len({(p, c.lower()) for c,p,_,_ in D}) == len(D), "duplicate coaster in the same park"

def q(x): return "'" + x.replace("'","''") + "'"

L = []
L.append("-- seed  Catalogue seed, generated by gerar_seed.py. Do not edit by hand.")
L.append("--")
L.append(f"-- {len(D)} real coasters, {len(parks_seen)} parks, {len(fabs)} manufacturers,")
L.append(f"-- {len(types_seen)} track types, {len(countries)} countries. SOW 6 asks for 'roughly 30 to 50'.")
L.append("--")
L.append("-- Runs as the database owner (a migration), so RLS does not get in the way. No client")
L.append("-- can make these inserts: the catalogue policies require is_admin().")
L.append("")
L.append("insert into public.parks (name, country_code) values")
L.append(",\n".join(f"  ({q(p)}, {q(COUNTRY[p])})" for p in parks_seen) + ";")
L.append("")
L.append("insert into public.manufacturers (name) values")
L.append(",\n".join(f"  ({q(f)})" for f in fabs) + ";")
L.append("")
L.append("insert into public.coasters (name, park_id, manufacturer_id, track_type) values")
linhas = []
for c,p,f,t in D:
    m = f"(select id from public.manufacturers where name = {q(f)})" if f else "null"
    linhas.append(f"  ({q(c)},\n     (select id from public.parks where name = {q(p)}),\n     {m},\n     {q(t)})")
L.append(",\n".join(linhas) + ";")
L.append("")
L.append("-- check: if the counts do not match, the build stops here")
L.append("do $$ begin")
L.append(f"  if (select count(*) from public.coasters) <> {len(D)} then")
L.append(f"    raise exception 'seed: expected {len(D)} coasters, found %', (select count(*) from public.coasters);")
L.append("  end if;")
L.append(f"  if (select count(*) from public.parks) <> {len(parks_seen)} then")
L.append("    raise exception 'seed: wrong park count';")
L.append("  end if;")
L.append(f"  if (select count(*) from public.manufacturers) <> {len(fabs)} then")
L.append("    raise exception 'seed: wrong manufacturer count';")
L.append("  end if;")
L.append("end $$;")
open("0006_seed.sql","w").write("\n".join(L) + "\n")

print(f"coasters      {len(D)}")
print(f"parks         {len(parks_seen)}  ({sum(1 for p in parks_seen if COUNTRY[p]=='GB')} GB, {sum(1 for p in parks_seen if COUNTRY[p]=='US')} US)")
print(f"manufacturers {len(fabs)}")
print(f"track types   {len(types_seen)}  {dict(collections.Counter(t for *_,t in D))}")
print(f"countries     {len(countries)}  {dict(collections.Counter(COUNTRY[p] for _,p,_,_ in D))}")
print("\nmanufacturers:", ", ".join(fabs))
