-- 0006_seed.sql  Catalogo semente, gerado por gerar_seed.py. Nao editar a mao.
--
-- 46 montanhas-russas reais, 10 parques, 14 fabricantes,
-- 3 tipos de trilho, 2 paises. O SOW 6 pede 'roughly 30 to 50'.
--
-- Roda como dono do banco (migration), entao a RLS nao atrapalha. Nenhum cliente
-- consegue fazer estes inserts: as politicas de catalogo exigem is_admin().

insert into public.parks (name, country_code) values
  ('Alton Towers', 'GB'),
  ('Blackpool Pleasure Beach', 'GB'),
  ('Busch Gardens Tampa Bay', 'US'),
  ('Chessington World of Adventures', 'GB'),
  ('Hersheypark', 'US'),
  ('SeaWorld Orlando', 'US'),
  ('Thorpe Park', 'GB'),
  ('Universal Epic Universe', 'US'),
  ('Universal Islands of Adventure', 'US'),
  ('Universal Studios Florida', 'US');

insert into public.manufacturers (name) values
  ('Arrow Dynamics'),
  ('Bolliger & Mabillard'),
  ('Charles Paige'),
  ('Gerstlauer'),
  ('Great Coasters International'),
  ('Intamin'),
  ('John A. Miller'),
  ('Mack Rides'),
  ('Maurer Rides'),
  ('Philadelphia Toboggan Coasters'),
  ('Premier Rides'),
  ('Rocky Mountain Construction'),
  ('Schwarzkopf'),
  ('Vekoma');

insert into public.coasters (name, park_id, manufacturer_id, track_type) values
  ('Nemesis Reborn',
     (select id from public.parks where name = 'Alton Towers'),
     (select id from public.manufacturers where name = 'Bolliger & Mabillard'),
     'steel'),
  ('Oblivion',
     (select id from public.parks where name = 'Alton Towers'),
     (select id from public.manufacturers where name = 'Bolliger & Mabillard'),
     'steel'),
  ('The Smiler',
     (select id from public.parks where name = 'Alton Towers'),
     (select id from public.manufacturers where name = 'Gerstlauer'),
     'steel'),
  ('Wicker Man',
     (select id from public.parks where name = 'Alton Towers'),
     (select id from public.manufacturers where name = 'Great Coasters International'),
     'wooden'),
  ('Rita',
     (select id from public.parks where name = 'Alton Towers'),
     (select id from public.manufacturers where name = 'Intamin'),
     'steel'),
  ('Th13teen',
     (select id from public.parks where name = 'Alton Towers'),
     (select id from public.manufacturers where name = 'Intamin'),
     'steel'),
  ('Stealth',
     (select id from public.parks where name = 'Thorpe Park'),
     (select id from public.manufacturers where name = 'Intamin'),
     'steel'),
  ('Nemesis Inferno',
     (select id from public.parks where name = 'Thorpe Park'),
     (select id from public.manufacturers where name = 'Bolliger & Mabillard'),
     'steel'),
  ('Colossus',
     (select id from public.parks where name = 'Thorpe Park'),
     (select id from public.manufacturers where name = 'Intamin'),
     'steel'),
  ('The Swarm',
     (select id from public.parks where name = 'Thorpe Park'),
     (select id from public.manufacturers where name = 'Bolliger & Mabillard'),
     'steel'),
  ('Hyperia',
     (select id from public.parks where name = 'Thorpe Park'),
     (select id from public.manufacturers where name = 'Mack Rides'),
     'steel'),
  ('The Big One',
     (select id from public.parks where name = 'Blackpool Pleasure Beach'),
     (select id from public.manufacturers where name = 'Arrow Dynamics'),
     'steel'),
  ('Icon',
     (select id from public.parks where name = 'Blackpool Pleasure Beach'),
     (select id from public.manufacturers where name = 'Mack Rides'),
     'steel'),
  ('Grand National',
     (select id from public.parks where name = 'Blackpool Pleasure Beach'),
     (select id from public.manufacturers where name = 'Charles Paige'),
     'wooden'),
  ('Big Dipper',
     (select id from public.parks where name = 'Blackpool Pleasure Beach'),
     (select id from public.manufacturers where name = 'John A. Miller'),
     'wooden'),
  ('Mandrill Mayhem',
     (select id from public.parks where name = 'Chessington World of Adventures'),
     (select id from public.manufacturers where name = 'Vekoma'),
     'steel'),
  ('Vampire',
     (select id from public.parks where name = 'Chessington World of Adventures'),
     (select id from public.manufacturers where name = 'Arrow Dynamics'),
     'steel'),
  ('The Incredible Hulk Coaster',
     (select id from public.parks where name = 'Universal Islands of Adventure'),
     (select id from public.manufacturers where name = 'Bolliger & Mabillard'),
     'steel'),
  ('Jurassic World VelociCoaster',
     (select id from public.parks where name = 'Universal Islands of Adventure'),
     (select id from public.manufacturers where name = 'Intamin'),
     'steel'),
  ('Hagrid''s Magical Creatures Motorbike Adventure',
     (select id from public.parks where name = 'Universal Islands of Adventure'),
     (select id from public.manufacturers where name = 'Intamin'),
     'steel'),
  ('Hollywood Rip Ride Rockit',
     (select id from public.parks where name = 'Universal Studios Florida'),
     (select id from public.manufacturers where name = 'Maurer Rides'),
     'steel'),
  ('Revenge of the Mummy',
     (select id from public.parks where name = 'Universal Studios Florida'),
     (select id from public.manufacturers where name = 'Premier Rides'),
     'steel'),
  ('Stardust Racers',
     (select id from public.parks where name = 'Universal Epic Universe'),
     (select id from public.manufacturers where name = 'Mack Rides'),
     'steel'),
  ('Curse of the Werewolf',
     (select id from public.parks where name = 'Universal Epic Universe'),
     (select id from public.manufacturers where name = 'Mack Rides'),
     'steel'),
  ('Hiccup''s Wing Gliders',
     (select id from public.parks where name = 'Universal Epic Universe'),
     (select id from public.manufacturers where name = 'Intamin'),
     'steel'),
  ('Mine-Cart Madness',
     (select id from public.parks where name = 'Universal Epic Universe'),
     (select id from public.manufacturers where name = 'Intamin'),
     'steel'),
  ('Mako',
     (select id from public.parks where name = 'SeaWorld Orlando'),
     (select id from public.manufacturers where name = 'Bolliger & Mabillard'),
     'steel'),
  ('Manta',
     (select id from public.parks where name = 'SeaWorld Orlando'),
     (select id from public.manufacturers where name = 'Bolliger & Mabillard'),
     'steel'),
  ('Kraken',
     (select id from public.parks where name = 'SeaWorld Orlando'),
     (select id from public.manufacturers where name = 'Bolliger & Mabillard'),
     'steel'),
  ('Ice Breaker',
     (select id from public.parks where name = 'SeaWorld Orlando'),
     (select id from public.manufacturers where name = 'Premier Rides'),
     'steel'),
  ('Pipeline: The Surf Coaster',
     (select id from public.parks where name = 'SeaWorld Orlando'),
     (select id from public.manufacturers where name = 'Bolliger & Mabillard'),
     'steel'),
  ('Iron Gwazi',
     (select id from public.parks where name = 'Busch Gardens Tampa Bay'),
     (select id from public.manufacturers where name = 'Rocky Mountain Construction'),
     'hybrid'),
  ('SheiKra',
     (select id from public.parks where name = 'Busch Gardens Tampa Bay'),
     (select id from public.manufacturers where name = 'Bolliger & Mabillard'),
     'steel'),
  ('Montu',
     (select id from public.parks where name = 'Busch Gardens Tampa Bay'),
     (select id from public.manufacturers where name = 'Bolliger & Mabillard'),
     'steel'),
  ('Kumba',
     (select id from public.parks where name = 'Busch Gardens Tampa Bay'),
     (select id from public.manufacturers where name = 'Bolliger & Mabillard'),
     'steel'),
  ('Cheetah Hunt',
     (select id from public.parks where name = 'Busch Gardens Tampa Bay'),
     (select id from public.manufacturers where name = 'Intamin'),
     'steel'),
  ('Skyrush',
     (select id from public.parks where name = 'Hersheypark'),
     (select id from public.manufacturers where name = 'Intamin'),
     'steel'),
  ('Candymonium',
     (select id from public.parks where name = 'Hersheypark'),
     (select id from public.manufacturers where name = 'Bolliger & Mabillard'),
     'steel'),
  ('Wildcat''s Revenge',
     (select id from public.parks where name = 'Hersheypark'),
     (select id from public.manufacturers where name = 'Rocky Mountain Construction'),
     'hybrid'),
  ('Great Bear',
     (select id from public.parks where name = 'Hersheypark'),
     (select id from public.manufacturers where name = 'Bolliger & Mabillard'),
     'steel'),
  ('Storm Runner',
     (select id from public.parks where name = 'Hersheypark'),
     (select id from public.manufacturers where name = 'Intamin'),
     'steel'),
  ('Fahrenheit',
     (select id from public.parks where name = 'Hersheypark'),
     (select id from public.manufacturers where name = 'Intamin'),
     'steel'),
  ('Lightning Racer',
     (select id from public.parks where name = 'Hersheypark'),
     (select id from public.manufacturers where name = 'Great Coasters International'),
     'wooden'),
  ('Comet',
     (select id from public.parks where name = 'Hersheypark'),
     (select id from public.manufacturers where name = 'Philadelphia Toboggan Coasters'),
     'wooden'),
  ('Laff Trakk',
     (select id from public.parks where name = 'Hersheypark'),
     (select id from public.manufacturers where name = 'Maurer Rides'),
     'steel'),
  ('Sooperdooperlooper',
     (select id from public.parks where name = 'Hersheypark'),
     (select id from public.manufacturers where name = 'Schwarzkopf'),
     'steel');

-- conferencia: se a contagem nao bater, o build para aqui
do $$ begin
  if (select count(*) from public.coasters) <> 46 then
    raise exception 'seed: esperava 46 coasters, achei %', (select count(*) from public.coasters);
  end if;
  if (select count(*) from public.parks) <> 10 then
    raise exception 'seed: contagem de parques errada';
  end if;
  if (select count(*) from public.manufacturers) <> 14 then
    raise exception 'seed: contagem de fabricantes errada';
  end if;
end $$;
